[database]
url = "postgres://postgres:postgres@localhost:5432/postgres"

[runner]
num-threads = 4
num-runs = 10

[archive]
output-dir = "./archive"
command = [
    "wget",
    "--accept",
    "htm,html,css,js,jpg,jpeg,png,gif,bmp,svg,webp,woff,woff2,ttf,otf,php,aspx",
    "--mirror",
    "--tries",
    "2",
    "--no-parent",
    "--user-agent",
    "Mozilla/5.0",
    "--convert-links",
    "--adjust-extension",
    "{url}",
]
